from typing import Protocol

from app.models.project import Project


class ProjectRepository(Protocol):
    def create_project(self, project: Project) -> Project: ...

    def list_projects(self, *, include_deleted: bool = False) -> list[Project]: ...

    def get_project(self, project_id: str) -> Project | None: ...

    def save_project(self, project: Project) -> Project: ...

    def get_project_for_chapter(self, chapter_id: str) -> Project | None: ...

    def get_project_for_scene(self, scene_id: str) -> Project | None: ...
